name: Omar's Blog
title: Omar's Blog | A blog about Programming (and movies)
description: Here I write about my thoughts.
tags:
  - blog
  - template
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /feed.xml
# email: youremail@test.com
# See: https://disqus.com/
disqus_username: omar45
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
